services:
  rabbitmq:
    image: rabbitmq:4.2.5-management
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
    container_name: rabbitmq-reshala
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json" -rabbitmq_management path_prefix "/admin/rabbit"'    
    ports:
      - 15672:15672
      - 5672:5672