spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/user_service_db
    username: ETA_DBUser
    password: ${DB_PASSWORD}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: service-user
    password: servicepassword
    virtual-host: universal-host
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2s
          multiplier: 2.0
          max-interval: 10s

minio:
  endpoint: http://minio:9000
  base:
    path: https://api.ucust.n4d3sh1k4.site/s3/user-service/
