services:
  minio:
    image: minio/minio:latest
    container_name: minio-reshala
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:8180/admin/minio/
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 admin password123;
      
      # spring orcestrator

      mc mb local/dataset-images;
      mc mb local/temp-images;

      mc anonymous set download local/dataset-images;
      mc anonymous set download local/temp-images;

      mc admin user add local monitor monitorpassword;

      mc admin policy attach local readwrite --user monitor;

      exit 0;
      "

volumes:
  minio_data: