"""
Dry-Run Mock Integration Test Suite for UCust.AI.
Simulates all AI agent inferences (Saiga 3 LLM, LTX-2.3 ComfyUI) and external parsers with fast async mocks.
Tests FSM state transitions, activate()/standby() VRAM hooks, pending post exports, and multi-platform publishing across Telegram, VK, Instagram, OK, and MAX.
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys

# Set USE_MOCKS environment variable to enable mock dry-run mode
os.environ["USE_MOCKS"] = "true"

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from bridge.api_controller import (
    ProcessRequest,
    get_pending_posts,
    get_status,
    process_request,
    publish_post,
)
from core.agents import (
    AgentContext,
    Agent_Analyst,
    Agent_Copywriter,
    Agent_FactChecker,
    Agent_Interviewer,
    Agent_Visual_Director,
)
from core.orchestrator import AgentState, build_default_orchestrator
from publishers import get_publisher
from schemas.models import (
    CopywritingFramework,
    PublishRequestSchema,
    QuestionnaireStep1,
    QuestionnaireStep2,
    QuestionnaireStep3,
    QuestionnaireStep4,
    QuestionnaireStep5,
    UserQuestionnaire,
)
from storage.db import init_db

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("test_dry_run_mocks")


class MockBackgroundRunner:
    """Simulates FastAPI BackgroundTasks in async tests."""

    def add_task(self, func, *args, **kwargs):
        if asyncio.iscoroutinefunction(func):
            asyncio.create_task(func(*args, **kwargs))
        else:
            func(*args, **kwargs)


async def run_dry_run_mocks_test():
    logger.info("=== STARTING DRY-RUN MOCK INTEGRATION TEST (USE_MOCKS=true) ===")

    # Step 1: Verify Individual Agent Activate/Run/Standby Lifecycle & VRAM Hooks
    logger.info("--- Step 1: Verifying Agent Lifecycle & VRAM Memory Hooks ---")
    mock_questionnaire = UserQuestionnaire(
        step1=QuestionnaireStep1(
            business_name="UCust Fitness",
            mission="Здоровый образ жизни доступен каждому",
            region="Москва и регионы РФ",
        ),
        step2=QuestionnaireStep2(
            target_audience="Мужчины и женщины 18-35 лет",
            demographics="Городское население, средний доход",
            pain_points="Нехватка времени на спортзалы и правильное питание",
        ),
        step3=QuestionnaireStep3(
            tone_of_voice="Энергичный, мотивирующий",
            content_formats="Посты, короткие ролики и сторис",
            taboo_topics="Негатив, ненаучные диеты, спам",
        ),
        step4=QuestionnaireStep4(
            goals="Увеличение базы клиентов онлайн-тренингов",
            kpi="Количество целевых заявок",
            frequency="3 раза в неделю",
        ),
        step5=QuestionnaireStep5(
            competitors="Сеть А, Онлайн-клуб Б",
            references="Инстаграм тренеров X, Y",
            additional_notes="Приоритет на видеоконтент LTX-2.3",
        ),
    )
    context = AgentContext(questionnaire=mock_questionnaire)

    agents_to_test = [
        Agent_Interviewer(),
        Agent_Analyst(),
        Agent_Copywriter(),
        Agent_FactChecker(),
        Agent_Visual_Director(),
    ]

    for agent in agents_to_test:
        logger.info("[Lifecycle Check] Activating agent '%s'...", agent.name)
        await agent.activate(context)
        context = await agent.run(context)
        logger.info("[Lifecycle Check] Putting agent '%s' into standby (VRAM release)...", agent.name)
        await agent.standby(context)
        assert len(context.logs) > 0, f"Agent {agent.name} should record logs"

    logger.info("[OK] All 5 agents completed activate -> run -> standby lifecycle successfully.")
    assert context.swot is not None, "SWOT analysis must be populated by Mock Analyst"
    assert context.post_draft is not None, "Post draft must be generated by Mock Copywriter/FactChecker"
    assert context.post_draft.local_video_path is not None, "Mock Visual Director must bind local video file path"
    assert os.path.exists(context.post_draft.local_video_path), f"Mock video file must physically exist at {context.post_draft.local_video_path}"
    logger.info("[OK] Verified mock video physical file creation at '%s'.", context.post_draft.local_video_path)

    # Step 2: Verify Publisher Factory Direct Mock Calls (Telegram, VK, Instagram, OK, MAX)
    logger.info("--- Step 2: Verifying Social Media Publishers Direct Execution ---")
    platforms = ["telegram", "vk", "instagram", "ok", "max"]
    video_path = context.post_draft.local_video_path

    for platform in platforms:
        pub = get_publisher(platform)
        ok_res = await pub.publish(text="Тестовый пост для сухой проверки", media_path=video_path)
        assert ok_res is True, f"Publisher '{platform}' should succeed in mock mode"
        logger.info("[OK] Direct publish call to '%s' returned True.", platform)

    # Step 3: End-to-End API Pipeline Test (Process -> Pending -> Publish)
    logger.info("--- Step 3: End-to-End API Controller Dry Run (FastAPI + SQL Storage) ---")
    await init_db()
    bg_tasks = MockBackgroundRunner()

    proc_req = ProcessRequest(
        user_id="dry_run_test_user_101",
        framework=CopywritingFramework.PAS,
    )
    proc_resp = await process_request(payload=proc_req, background_tasks=bg_tasks, session=None)
    job_id = proc_resp.job_id
    logger.info("[OK] API Process request accepted with job_id=%d", job_id)

    # Wait for FSM background execution
    await asyncio.sleep(0.4)

    # Step 4: Verify GET /api/v1/posts/pending
    pending_list = await get_pending_posts(session=None)
    assert len(pending_list) >= 1, "Expected at least 1 pending post for review"
    matching = next((p for p in pending_list if p.job_id == job_id), None)
    assert matching is not None, f"Expected pending post for job_id={job_id}"
    assert matching.post_text is not None
    assert matching.local_video_path is not None
    logger.info("[OK] GET /api/v1/posts/pending retrieved post #%d with local_video_path='%s'", job_id, matching.local_video_path)

    # Step 5: Verify POST /api/v1/posts/{post_id}/publish for all 5 platforms
    pub_req = PublishRequestSchema(
        platforms=["telegram", "vk", "instagram", "ok", "max"],
        custom_caption="Утвержденный пост для рассылки во все 5 соцсетей!",
    )
    pub_resp = await publish_post(post_id=job_id, payload=pub_req, session=None)

    assert pub_resp["status"] == "PUBLISHED"
    results = pub_resp["publish_results"]
    for p in platforms:
        assert results.get(p) is True, f"Publish result for {p} must be True"
    logger.info("[OK] POST /api/v1/posts/%d/publish published to all 5 platforms: %s", job_id, list(results.keys()))

    # Step 6: Verify final status in DB
    final_task = await get_status(job_id=job_id, session=None)
    assert final_task.status == "PUBLISHED"
    logger.info("[OK] DB status verified as PUBLISHED for job_id=%d", job_id)

    logger.info("=== DRY-RUN MOCK INTEGRATION TEST PASSED 100% ===")


if __name__ == "__main__":
    asyncio.run(run_dry_run_mocks_test())
